services:
  api:
    image: ghcr.io/live4dev/achievements:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head && python web.py"

  bot:
    image: ghcr.io/live4dev/achievements:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - api
    command: python bot.py

volumes:
  postgres_data:
