services:
  api:
    image: ghcr.io/live4dev/achievements:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    command: >
      sh -c "alembic upgrade head && python web.py"

  bot:
    image: ghcr.io/live4dev/achievements:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    command: python bot.py
